const cardList = [
	{ suite: "hearts", color: "red", name: "Ace", score: 1, symbol: "🂱" },
	{ suite: "hearts", color: "red", name: "2", score: 2, symbol: "🂲" },
	{ suite: "hearts", color: "red", name: "3", score: 3, symbol: "🂳" },
	{ suite: "hearts", color: "red", name: "4", score: 4, symbol: "🂴" },
	{ suite: "hearts", color: "red", name: "5", score: 5, symbol: "🂵" },
	{ suite: "hearts", color: "red", name: "6", score: 6, symbol: "🂶" },
	{ suite: "hearts", color: "red", name: "7", score: 7, symbol: "🂷" },
	{ suite: "hearts", color: "red", name: "8", score: 8, symbol: "🂸" },
	{ suite: "hearts", color: "red", name: "9", score: 9, symbol: "🂹" },
	{ suite: "hearts", color: "red", name: "10", score: 10, symbol: "🂺" },
	{ suite: "hearts", color: "red", name: "Jack", score: 10, symbol: "🂻" },
	{ suite: "hearts", color: "red", name: "Queen", score: 10, symbol: "🂽" },
	{ suite: "hearts", color: "red", name: "King", score: 10, symbol: "🂾" },
	{
		suite: "diamonds",
		color: "red",
		name: "Ace",
		score: 1,
		symbol: "🃁",
	},
	{ suite: "diamonds", color: "red", name: "2", score: 2, symbol: "🃂" },
	{ suite: "diamonds", color: "red", name: "3", score: 3, symbol: "🃃" },
	{ suite: "diamonds", color: "red", name: "4", score: 4, symbol: "🃄" },
	{ suite: "diamonds", color: "red", name: "5", score: 5, symbol: "🃅" },
	{ suite: "diamonds", color: "red", name: "6", score: 6, symbol: "🃆" },
	{ suite: "diamonds", color: "red", name: "7", score: 7, symbol: "🃇" },
	{ suite: "diamonds", color: "red", name: "8", score: 8, symbol: "🃈" },
	{ suite: "diamonds", color: "red", name: "9", score: 9, symbol: "🃉" },
	{ suite: "diamonds", color: "red", name: "10", score: 10, symbol: "🃊" },
	{ suite: "diamonds", color: "red", name: "Jack", score: 10, symbol: "🃋" },
	{
		suite: "diamonds",
		color: "red",
		name: "Queen",
		score: 10,
		symbol: "🃍",
	},
	{ suite: "diamonds", color: "red", name: "King", score: 10, symbol: "🃎" },
	{
		suite: "clubs",
		color: "black",
		name: "Ace",
		score: 1,
		symbol: "🃑",
	},
	{ suite: "clubs", color: "black", name: "2", score: 2, symbol: "🃒" },
	{ suite: "clubs", color: "black", name: "3", score: 3, symbol: "🃓" },
	{ suite: "clubs", color: "black", name: "4", score: 4, symbol: "🃔" },
	{ suite: "clubs", color: "black", name: "5", score: 5, symbol: "🃕" },
	{ suite: "clubs", color: "black", name: "6", score: 6, symbol: "🃖" },
	{ suite: "clubs", color: "black", name: "7", score: 7, symbol: "🃗" },
	{ suite: "clubs", color: "black", name: "8", score: 8, symbol: "🃘" },
	{ suite: "clubs", color: "black", name: "9", score: 9, symbol: "🃙" },
	{ suite: "clubs", color: "black", name: "10", score: 10, symbol: "🃚" },
	{ suite: "clubs", color: "black", name: "Jack", score: 10, symbol: "🃛" },
	{ suite: "clubs", color: "black", name: "Queen", score: 10, symbol: "🃝" },
	{ suite: "clubs", color: "black", name: "King", score: 10, symbol: "🃞" },
	{
		suite: "spades",
		color: "black",
		name: "Ace",
		score: 1,
		symbol: "🂡",
	},
	{ suite: "spades", color: "black", name: "2", score: 2, symbol: "🂢" },
	{ suite: "spades", color: "black", name: "3", score: 3, symbol: "🂣" },
	{ suite: "spades", color: "black", name: "4", score: 4, symbol: "🂤" },
	{ suite: "spades", color: "black", name: "5", score: 5, symbol: "🂥" },
	{ suite: "spades", color: "black", name: "6", score: 6, symbol: "🂦" },
	{ suite: "spades", color: "black", name: "7", score: 7, symbol: "🂧" },
	{ suite: "spades", color: "black", name: "8", score: 8, symbol: "🂨" },
	{ suite: "spades", color: "black", name: "9", score: 9, symbol: "🂩" },
	{ suite: "spades", color: "black", name: "10", score: 10, symbol: "🂪" },
	{ suite: "spades", color: "black", name: "Jack", score: 10, symbol: "🂫" },
	{
		suite: "spades",
		color: "black",
		name: "Queen",
		score: 10,
		symbol: "🂭",
	},
	{ suite: "spades", color: "black", name: "King", score: 10, symbol: "🂮" },
];
const cardAgents = [
	{
		name: "deck",
		el: $("#dealerDeck"),
		props: {
			decks: 2,
		},
	},
	{
		name: "dealer",
		el: $("#dealerHand"),
		props: {
			decks: 0,
		},
	},
	{
		name: "player",
		el: $("#playerHand"),
		props: {
			decks: 0,
		},
	},
];
const tokenAgents = [
	{
		name: "dealer",
		el: $("#dealerPot"),
		props: {
			count: 100,
		},
	},
	{
		name: "bet",
		el: $("#playerBet"),
		props: {
			count: 0,
		},
	},
	{
		name: "pot",
		el: $("#playerPot"),
		props: {
			count: 20,
		},
	},
];
